In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,{1:124}])
a

array([1, 2, 3, 4, {1: 124}], dtype=object)

In [4]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [5]:
#print dimensions of a,b, c and d
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:', c.ndim)
print('d dimension:', d.ndim)


a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [6]:
print(c.dtype)
print(d.dtype)

int64
int64


In [7]:
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of d: (2, 2, 3)


In [8]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
print(len(b))

3
