In [38]:
! pip install numpy

In [39]:
import numpy as np

In [40]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [42]:
np.zeros((5,5),dtype = 'int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
np.ones((5,5),dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.full((5,5), 8, dtype = 'int')

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [45]:
x = [1,2,3,4,5,6,7,8]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [46]:
# using arange() to generate numpy array x with number between 1 to 16
x = np.arange(1,17)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [47]:
n = x.reshape((4,4))
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
2


In [48]:
n1 = n.reshape((4,2,2))
print(n1)
print(n1.shape)
print(n1.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3


In [49]:
# create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [50]:
# get third element in array a
print(a[2])

6


In [51]:
# print 1st, 3rd, 5th and 7th element in array a
a[0:7:2]
a[2:5]

array([ 6,  8, 10])

In [52]:
# define an array 2-d a with[[1,2,3], [4,5,6], [7,8,9]] as its elements
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# print the third element from the 3rd row of a
print(a[1,2])

6


In [59]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# slice elements from 1st to 5th element from array array:
array[1:6]

array([2, 3, 4, 5, 6])

In [62]:
# slice elements from index 5 to the end of the array array:
array[5:]

array([ 6,  7,  8,  9, 10])

In [63]:
# slice elements from the begining to index5 (not included) in the array array:
array[:5]

array([1, 2, 3, 4, 5])

In [64]:
# print every other element from index 1 to index?
array[1:7:2]

array([2, 4, 6])

In [65]:
#return every other element from the entire array array:
array[0:10:2]

array([1, 3, 5, 7, 9])

In [66]:
# print array a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# in array 'a' print index2 from all the rows:
# print(a[:,2])
print(a[0,:])

[1 2 3]


In [68]:
print(a[0:2, 1:3])

[[2 3]
 [5 6]]


In [69]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# assign x2=x1
x2=x1 #view
#print x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [74]:
# change 1st element of x2 as 10
x2[0] = 10

In [75]:
# again print x1 and x2
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [76]:
print(id(x1))
print(id(x2))

138306755966800
138306755966800


In [77]:
# check memory share between x1 and x2
print(np.shares_memory(x1,x2))
print(id(x1))
print(id(x2))

True
138306755966800
138306755966800


In [83]:
# create a view of x1 and store it in x3
x3 = x1.view

In [84]:
# print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[10  1  2  3  4  5  6  7  8  9]
<built-in method view of numpy.ndarray object at 0x7dca0d0f3750>


In [86]:
# now create an array x4 which is copy of x1
x4 = np.copy(x1)

In [87]:
# change the last element of x4 as 900
x4[-1] = 900

In [88]:
# print both x1 and x4 to check if change reflected in both
print(x1)
print(x4)

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 900]


In [90]:
# check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1,x4)

138306755966800
138306759581712


False

In [91]:
# print a
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
# check if every element in array a greater than 3 or not using '>' notation
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [93]:
# get a list with all elements of array 'a' greater than 3
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [94]:
# get a list with all elements of array 'a' greater than 3 but less than 6
a[(a>2)&(a<=7)]

array([3, 4, 5, 6, 7])

In [95]:
# check if each element in array 'x1' equals array 'x4' using '==' notation
x1 == x4
print(x1)
print(x4)

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 900]


In [96]:
# print transpose of array 'a'
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [97]:
# print array 'a'
print("----------------")
print(a)

----------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
# stack x1 and x4 along columns
print(x1)
print(x4)
np.vstack((x1,x4))

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 900]


array([[ 10,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [99]:
# stack x1 and x4 along rows
np.hstack((x1,x4))

array([ 10,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

In [100]:
# insert values into array x1 before index 4 with elements of x4
print(x1)
print(x4)
np.insert(x1,4,x4)

[10  1  2  3  4  5  6  7  8  9]
[ 10   1   2   3   4   5   6   7   8 900]


array([ 10,   1,   2,   3,  10,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

In [101]:
# delete 2nd element from array x2
print(x2)
np.delete(x2,2)

[10  1  2  3  4  5  6  7  8  9]


array([10,  1,  3,  4,  5,  6,  7,  8,  9])

In [103]:
# defining a
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [104]:
# print trignometric sin value of each element of a
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [105]:
print(np.sin(30))

-0.9880316240928618


In [106]:
print(np.tan(20))

2.237160944224742


In [107]:
print((np.sin(a))/(np.cos(a)))

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [108]:
# print trignometric cos value of each element of a
print(np.cos(a))
print(np.tan(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [109]:
#  print exponential value of each elements of a
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [110]:
# print total sum of elements of a
np.sum(a)
np.int64(45)

np.int64(45)

In [111]:
# print sum in array a column wise
np.sum(a,axis = 0)

array([12, 15, 18])

In [112]:
# print sum in array a row wise
np.sum(a,axis = 1)

array([ 6, 15, 24])

In [113]:
# print median of array a
print(np.median(a))

5.0


In [114]:
# print mean of array a
print(np.mean(a))

5.0


In [116]:
# print sd of array a
np.std(a)

np.float64(2.581988897471611)

In [118]:
# print largest element present in array a
np.max(a)

np.int64(9)

In [119]:
# print sorted x4 array
np.sort(x4)

array([  1,   2,   3,   4,   5,   6,   7,   8,  10, 900])

In [120]:
# create a numpy array
arr = np.array([[12,14,17,19,24,27,35,38]])


In [121]:
# use numpy.where() with 1d arrays
arr1 = np.where(arr<17)
print(arr1)

(array([0, 0]), array([0, 1]))


In [122]:
print(dir(list))
print(dir(set))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', 

In [123]:
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35


In [124]:
ravel_arr = arr.ravel()
ravel_arr[0] = 1001
print(arr)
print(np.shares_memory (arr,ravel_arr))
print(np.shares_memory(x1,x2))

[[1001   14   17   19   24   27   35   38]]
True
True
